import Navigation from '@/components/navigation/Navigation';
import Providers from '@/redux/Providers';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Poppins } from 'next/font/google';
import './globals.css';

config.autoAddCss = false;
const poppins = Poppins({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'Aniline',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<Providers>
			<html lang="en">
				<body className={poppins.className}>
					<header>
						<Navigation />
					</header>
					<main>{children}</main>
				</body>
			</html>
		</Providers>
	);
}
